import nltk

base = [('eu sou admirada por muitos','alegria'),
        ('me sinto completamente amado','alegria'),
        ('amar e maravilhoso','alegria'),
        ('estou me sentindo muito animado novamente','alegria'),
        ('eu estou muito bem hoje','alegria'),
        ('que belo dia para dirigir um carro novo','alegria'),
        ('o dia est· muito bonito','alegria'),
        ('estou contente com o resultado do teste que fiz no dia de ontem','alegria'),
        ('o amor e lindo','alegria'),
        ('nossa amizade e amor vai durar para sempre', 'alegria'),
        ('estou amedrontado', 'medo'),
        ('ele esta me ameacando a dias', 'medo'),
        ('isso me deixa apavorada', 'medo'),
        ('este lugar e apavorante', 'medo'),
        ('se perdermos outro jogo seremos eliminados e isso me deixa com pavor', 'medo'),
        ('tome cuidado com o lobisomem', 'medo'),
        ('se eles descobrirem estamos encrencados', 'medo'),
        ('estou tremendo de medo', 'medo'),
        ('eu tenho muito medo dele', 'medo'),
        ('estou com medo do resultado dos meus testes', 'medo')]

#print(base[0])

basetreinamento = [
('este trabalho e agradavel','alegria'),
('gosto de ficar no seu aconchego','alegria'),
('fiz a adesao ao curso hoje','alegria'),
('eu sou admirada por muitos','alegria'),
('adoro como voce e','alegria'),
('adoro seu cabelo macio','alegria'),
('adoro a cor dos seus olhos','alegria'),
('somos tao amaveis um com o outro','alegria'),
('sinto uma grande afeicao por ele','alegria'),
('quero agradar meus filhos','alegria'),
('me sinto completamente amado','alegria'),
('eu amo voce','alegria'),
('que grande alivio','alegria'),
('a dor esta amenizando finalmente','alegria'),
('acho que me apaixonei','alegria'),
('amar e maravilhoso','alegria'),
('estou me sentindo muito animada','alegria'),
('me sinto muito bem hoje','alegria'),
('como o luar e belo','alegria'),
('o dia esta muito bonito','alegria'),
('nossa como sou afortunado','alegria'),
('as maravilhas do mundo','alegria'),
('recebi muito carinho hoje do meus colegas','alegria'),
('estou me sentindo reconfortada hoje','alegria'),
('e muito bom estar com os amigos','alegria'),
('estou muito contente com o resultado dos testes','alegria'),
('essa pintura esta bem brilhante','alegria'),
('temos agua em abundancia','alegria'),
('que roupa delicada','alegria'),
('voce e um grande comediante','alegria'),
('que bondade a sua em vir aqui','alegria'),
('o amor e lindo','alegria'),
('nossa amizade vai durar para sempre','alegria'),
('estou euforica com a noticia','alegria'),
('ele e realmente fiel a mim','alegria'),
('vou dar uma grande festa para comemorar meu aniversario','alegria'),
('gracas a deus que eu enxerguei o certo','alegria'),
('essa e a melhor escolhas de todas','alegria'),
('o mais incrivel e voce minha bela','alegria'),
('e tao engracado tentar explicar','alegria'),
('e emocionante estar neste lugar','alegria'),
('estou cativada pelo seu olhar','alegria'),
('estou loucamente apaixonada','alegria'),
('eu nunca tive duvidas','alegria'),
('estou rodeada pelo seu abraco','alegria'),
('eu vejo estrelas pelo caminho','alegria'),
('eu sinto o sol sempre que voce esta por perto','alegria'),
('eu estou sorrindo de orelha a orelha','alegria'),
('isso vale a pena','alegria'),
('finalmente voce colocou meu amor em primeiro lugar','alegria'),
('nos dancamos noite adentro','alegria'),
('seu amor e brilhante','alegria'),
('toquei muitos coracoes durante o meu caminho','alegria'),
('eu serei sua amiga e companheira','alegria'),
('voce me traz de volta a vida','alegria'),
('voce e como um sonho doce','alegria'),
('adoro este doce de frutas','alegria'),
('meu suco favorito','alegria'),
('estou agradecida pela ajuda','alegria'),
('e um enorme prazer ter voce em nossa equipe','alegria'),
('trabalhar em equipe e o melhor','alegria'),
('me sinto flutuando no ar','alegria'),
('a brisa esta agradavel hoje','alegria'),
('utimo e compativel','alegria'),
('somos compativeis um com o outro','alegria'),
('o orgao e compativel com o paciente','alegria'),
('estou contente fui aceita na faculdade','alegria'),
('fui aprovada no meu exame','alegria'),
('fui beneficiada pela minha empresa','alegria'),
('eu sou muito cativante','alegria'),
('estou contente com o apoio','alegria'),
('como este lugar e confortavel','alegria'),
('e bom estar quente neste frio','alegria'),
('um elogio nunca e demais','alegria'),
('vou te chamar para comemorar','alegria'),
('e desejavel a sua presenca em nossa apresentacao','alegria'),
('sou muito grata a voce','alegria'),
('me dedico muito naquilo que faco','alegria'),
('estou completamente apaixonada ','alegria'),
('vamos agitar essa noite ','alegria'),
('voce significa muito para mim','alegria'),
('vamos agir sem preconceitos e julgamentos','alegria'),
('finalmente completei a minha colecao, maravilhoso','alegria'),
('eu sou sua rainha ','alegria'),
('satisfatoriamente eu anuncio o vencedor dos jogos','alegria'),
('voce me atrai facilmente ','alegria'),
('aquele rapaz e extremamente atraente','alegria'),
('sinto-me viva ','alegria'),
('sinto-me em paz ','alegria'),
('estamos tendo muito lucro','alegria'),
('muito bem esta tudo em ordem agora ','alegria'),
('podemos arrumar um emprego juntos ','alegria'),
('a arrumacao esta terminada, que alivio','alegria'),
('o cancer e benigno ','alegria'),
('o amor e abundante','alegria'),
('vamos ser caridosos este natal','alegria'),
('com todo esse charme voce ira atrair a todos','alegria'),
('nossa como voce e charmoso querido ','alegria'),
('sou querida pelos meu amigos','alegria'),
('seja cuidadoso com os meus sentimentos','alegria'),
('estou comovido com tamanha caridade','alegria'),
('um cha quente e reconfortante','alegria'),
('que alegria ter voces aqui ','alegria'),
('vamos aplaudir o vencedor ','alegria'),
('palmas para a aniversariante','alegria'),
('desejo a voce tudo de bom','alegria'),
('hora de apreciar um bom vinho','alegria'),
('aprecio sua presenca em minha escola','alegria'),
('anseio por seus proximos trabalhos','alegria'),
('maravilhoso jogo amistoso','alegria'),
('e otimo que os animos tenham se apaziguado','alegria'),
('concretizei finalmente meu sonho','alegria'),

('voce e abominavel','desgosto'),
('abomino a maneira como voce age','desgosto'),
('estou adoentado','desgosto'),
('meu pai esta adoentado','desgosto'),
('estamos todos doentes','desgosto'),
('essa situacao e muito amarga','desgosto'),
('disse adeus amargamente','desgosto'),
('tenho antipatia por aquela pessoa','desgosto'),
('como pode ser tao antipatica!','desgosto'),
('que horrivel seu asqueroso','desgosto'),
('tenho aversao a gente como voce','desgosto'),
('isso tudo e so chateacao','desgosto'),
('estou muito chateada com suas mentiras','desgosto'),
('tao desagradavel','desgosto'),
('isso me desagrada completamente','desgosto'),
('te desagrada isso','desgosto'),
('estou com enjoos terriveis','desgosto'),
('todos estao enfermos','desgosto'),
('foi uma enfermidade terrivel','desgosto'),
('isso e muito grave','desgosto'),
('nao seja tao grosseiro','desgosto'),
('voce fez uma manobra ilegal','desgosto'),
('sua indecente, nao tem vergonha?','desgosto'),
('voce e malvado com as criancas','desgosto'),
('que comentario maldoso','desgosto'),
('sem escrupulos voce manipula a tudo','desgosto'),
('sinto repulsa por voce','desgosto'),
('e repulsivo a maneira como olha para as pessoas','desgosto'),
('estou indisposta','desgosto'),
('a indisposicao me atacou hoje','desgosto'),
('acho que vou vomitar','desgosto'),
('tem muito vomito la','desgosto'),
('que incomodo essa dor','desgosto'),
('nao me incomode nunca mais','desgosto'),
('suas bobagens estao nos incomodando','desgosto'),
('que nojo olha toda essa sujeira','desgosto'),
('como isso esta sujo','desgosto'),
('tenho nauseas so de lembrar','desgosto'),
('me sinto nauseada com o cheiro desta comida','desgosto'),
('voce esta obstruindo a passagem de ar','desgosto'),
('voce esta terrivelmente doente','desgosto'),
('olhe que feia esta roupa','desgosto'),
('que atitude deploravel','desgosto'),
('nossa como voce e feio','desgosto'),
('muito mau tudo isso','desgosto'),
('estou desgostoso com voce','desgosto'),
('voce cortou o meu assunto','desgosto'),
('para que tanta chateacao?','desgosto'),
('esse perfume e enjoativo','desgosto'),
('ser perigoso nao e nada bom','desgosto'),
('voce e perigoso demais para minha filhas','desgosto'),
('que fetido este esgoto','desgosto'),
('que fedido voce esta','desgosto'),
('que cachorro mal cheiroso','desgosto'),
('ora que ultraje','desgosto'),
('e ultrajante da sua parte','desgosto'),
('situacao desagradavel essa','desgosto'),
('voce so me da desgosto','desgosto'),
('tenho aversao a pessoas assim','desgosto'),
('antipatia e um mal da sociedade','desgosto'),
('que criatura abominavel','desgosto'),
('e depressiva a maneira como voce ve o mundo','desgosto'),
('me desagrada sua presenca na festa','desgosto'),
('sinto asco dessa coisa','desgosto'),
('que hediondo!','desgosto'),
('vou golfar o cafe fora','desgosto'),
('hora que garota detestavel!','desgosto'),
('estou nauseada','desgosto'),
('isso que voce disse foi muito grave','desgosto'),
('nao seja obsceno na frente das criancas','desgosto'),
('nao seja rude com as visitas','desgosto'),
('esse assunto me da repulsa','desgosto'),
('que crianca terrivelmente travessa','desgosto'),
('que crianca mal educada','desgosto'),
('estou indisposta em te dar o divorcio','desgosto'),
('tao patetico, nao tem nada mais rude para dizer?','desgosto'),
('por motivo torpe, com emprego de meio cruel e com impossibilidade de defesa para a vitima','desgosto'),
('a inveja e tao vil e vergonhosa que ninguem se atreve a confessa-la','desgosto'),
('o miseravel receio de ser sentimental e o mais vil de todos os receios modernos','desgosto'),
('travesso gato quando fica com saudades do dono mija em seu sapato','desgosto'),
('isso e um ato detestavel e covarde','desgosto'),
('revelam apenas o que e destrutivo e detestavel para o povo','desgosto'),
('nao sei como e a vida de um patife, mas a de um homem honesto e abominavel','desgosto'),
('ha coisas que temos que suportar para nao acharmos a vida insuportavel','desgosto'),
('as injurias do tempo e as injusticas do homem','desgosto'),
('odioso e desumano','desgosto'),
('voce nao publicara conteudo odiento, pornografico ou ameacador','desgosto'),
('rancoroso e reprimido','desgosto'),
('nao ha animal mais degradante, estupido, covarde, lamentavel, egoista, rancoroso e invejoso do que o homem','desgosto'),
('o virulento debate ente politicos','desgosto'),

('eu imploro, nao me matem!','medo'),
('tem certeza que nao e perigoso?','medo'),
('nao tenho certeza se e seguro','medo'),
('tenho que correr pra nao me pegarem','medo'),
('socorro! ele queria roubar os meus doces!','medo'),
('esse cara esta me perseguindo','medo'),
('nao entro la, e um lugar muito perigoso','medo'),
('este lugar continua assustador','medo'),
('na selva tem muitos animais perigosos','medo'),
('avancem com cautela','medo'),
('este lugar esta silencioso demais, cuidado!','medo'),
('por favor, deixe-me viver!','medo'),
('vou ficar sem mesada se tirar nota baixa','medo'),
('parece que tem olhos nos vigiando','medo'),
('eu temo que a sentenca do juiz possa ser negativa','medo'),
('mas essa missao e arriscada','medo'),
('salve-se quem puder!','medo'),
('meu plano pode ser descoberto','medo'),
('nao tive culpa, juro, nao fui eu','medo'),
('tenho que tomar cuidado com o lobisomem','medo'),
('se eu nao achar, ele vai descobrir a verdade','medo'),
('meu deus, ele desapareceu!','medo'),
('tomara que eles nao me vejam aqui!','medo'),
('mantenha isso em segredo, se descobrirem estaremos ferrados','medo'),
('por favor, me soltem, eu sou inocente','medo'),
('estou ouvindo passos atras de mim','medo'),
('eu vou pedir socorro!','medo'),
('cuidado com as curvas na estrada','medo'),
('nao sei nao, parece perigoso','medo'),
('estou tremendo de medo!','medo'),
('socorro, eu vou cair!','medo'),
('eu nao vou ate a floresta negra, e muito perigoso','medo'),
('ouco passos na minha direcao','medo'),
('acho que esta arriscado demais','medo'),
('vamos voltar, e muito perigoso','medo'),
('fuja, se nao acabaremos mortos','medo'),
('receio por nao me livrar desta situacao','medo'),
('socorro! ele esta armado!','medo'),
('ei cuidado, voce vai bater no poste!','medo'),
('socorro, nos estamos afundando','medo'),
('e serio, cuidado com essa arma!','medo'),
('os tubaroes estao atacando!','medo'),
('sinto arrepios quando fico sozinho no escuro','medo'),
('calma, eu nao estou com o dinheiro','medo'),
('eu acho que estou sendo enganado','medo'),
('ligeiro, temos que fugir depressa','medo'),
('tem um crocodilo selvagem vindo para ca','medo'),
('se ficarmos quietos eles nao vao nos achar','medo'),
('fuja! o tigre parece faminto','medo'),
('estou sem saida, preciso de um milagre','medo'),
('tire isso de mim! socorro!','medo'),
('nao sei nadar, vou me afogar!','medo'),
('nao tenho certeza se e seguro','medo'),
('vou apanhar se meus pais verem meu boletim','medo'),
('nao consigo sair daqui!','medo'),
('se sair tao tarde, poderei ser assaltada','medo'),
('nao me deixe por favor!','medo'),
('espere, nao pode me largar aqui sozinho','medo'),
('temo pela sua seguranÁc','medo'),
('eu te entrego o dinheiro, por favor nao me mate!','medo'),
('ele vai levar todo o meu dinheiro','medo'),
('nao dirija tao rapido assim','medo'),
('me descobriram, irao me prender!','medo'),
('so espero que nao me facam nenhum mal','medo'),
('vou me afogar, me ajudem a sair da agua','medo'),
('nao estaremos a salvo aqui','medo'),
('nao quero nem pensar no que pode acontecer','medo'),
('nessa cidade e uma desgraca atras da outra','medo'),
('alguem esta me ligando, estou assustado','medo'),
('isso nao e remedio, nao me matem','medo'),
('eu nao confio nele, tenho que ter cautela','medo'),
('muita cautela','medo'),
('vou ser descoberto, meu deus','medo'),
('receio que terei de ir','medo'),
('a noite e muito perigosa','medo'),
('estou estremecendo com essa casa','medo'),
('olha aquela criatura se movendo monstruosamente','medo'),
('nao aguento este suspense','medo'),
('afugente os caes','medo'),
('estou chocado e amedrontado com este assassinato brutal','medo'),
('e preciso afugentar com impeto este medo do inferno','medo'),
('seu politicos usam suas forcas para afugentar e amedrontar o povo','medo'),
('o objetivo disso e apenas me amedrontar mais','medo'),
('isso me apavora','medo'),

('ele me feriu profundamente','raiva'),
('vou despejar minha colera em voce','raiva'),
('me sinto raivoso','raiva'),
('nao me contrarie','raiva'),
('vou destruir tudo  que foi construido','raiva'),
('nao consigo terminar este trabalho, e muito frustrante','raiva'),
('me frustra a sua presenca aqui','raiva'),
('esta comida me parece muito ruim','raiva'),
('vocc me destruiu','raiva'),
('estamos separados','raiva'),
('estou odiando este vestido','raiva'),
('nao pude comprar meu celular hoje','raiva'),
('ela e uma garota ruim','raiva'),
('estivemos em um show horroroso','raiva'),
('o ingresso estava muito caro','raiva'),
('se eu estragar tudo vai por agua abaixo','raiva'),
('nao possuo dinheiro algum','raiva'),
('sou muito pobre','raiva'),
('vai prejudicar a todos esta nova medida','raiva'),
('ficou ridiculo','raiva'),
('este sapato esta muito apertado','raiva'),
('a musica e uma ofensa aos meus ouvidos','raiva'),
('nao consigo terminar uma tarefa muito dificil','raiva'),
('reprovei em minha graduacao','raiva'),
('estou muito chateado com tudo','raiva'),
('eu odeio tudo em voce','raiva'),
('e um desprazer conhece-lo','raiva'),
('estou desperdicando minhas ferias','raiva'),
('e muito ruim este jogo','raiva'),
('vamos ter muito rancor pela frente','raiva'),
('nao achei que seria tao desagradavel','raiva'),
('vou vetar o orcamento ao cliente','raiva'),
('meus pais nao consentiram nosso casamento','raiva'),
('eu odiei este perfume','raiva'),
('seu descaso e frustrante','raiva'),
('me sinto completamente amarga','raiva'),
('desprezo muito o seu trabalho','raiva'),
('estamos frustados por voce','raiva'),
('vou infernizar a sua empresa','raiva'),
('estou furioso com estes valores','raiva'),
('obrigaram o rapaz a sair','raiva'),
('como ele pode deixar de lado?','raiva'),
('sao injurias sobre mim','raiva'),
('estou enfurecido com a situacao dessa empresa','raiva'),
('estou com o diabo no corpo','raiva'),
('isso foi diabolico','raiva'),
('tenho aversao a gente chata','raiva'),
('nao vou perdoar sua traicao','raiva'),
('esse dinheiro sujo e corrupto','raiva'),
('eles me crucificam o tempo todo','raiva'),
('eu vou enlouquecer com todo este barulho','raiva'),
('nao aguento todo esse assedio','raiva'),
('colera do dragao','raiva'),
('isso e ridiculo!','raiva'),
('da proxima vez vou fazer tudo sozinho','raiva'),
('seus tolos! deixaram ele escapar!','raiva'),
('jamais te perdoarei','raiva'),
('o que e isso? outra multa','raiva'),
('voce passou dos limites!','raiva'),
('sente-se e cale a boca','raiva'),
('ingratos, vermes, voces me pagam!','raiva'),
('saiam ja dai, se nao arranco voces dai!','raiva'),
('voce ja me causou problemas suficientes','raiva'),
('isso passou dos limites','raiva'),
('o que voce tem a ver com isso?','raiva'),
('nao vejo a hora de me livrar de voce','raiva'),
('ja entendi a jogada seus safados!','raiva'),
('voce nao merece piedade','raiva'),
('saia de perto de mim','raiva'),
('suma daqui, ou arranco seu couro!','raiva'),
('estou revoltado com essa situacao','raiva'),
('seu idiota!','raiva'),
('nao, eu nao vou te emprestar dinheiro!','raiva'),
('voce nao passa de um cafajeste! vai embora','raiva'),
('pare de frescura e va trabalhar','raiva'),
('eles merecem uma licao','raiva'),
('ainda estou muito bravo com voce','raiva'),
('eu preciso surrar aquele chantagista','raiva'),
('olha o que voce fez! derramou!','raiva'),
('voce esta pedindo para apanhar!','raiva'),
('me deixe em paz!','raiva'),
('morra maldito, morra!','raiva'),
('voce e mais irritante de perto','raiva'),
('e bom fechar o bico','raiva'),

('magicamente voce me surpreendeu','surpresa'),
('e imenso esse globo','surpresa'),
('isso e tremendamente interessante','surpresa'),
('meu bilhete for sorteado, inacreditavel!','surpresa'),
('um assalto a mao armada!','surpresa'),
('incrivel, cabe em qualquer lugar!','surpresa'),
('voce pos aqui?!','surpresa'),
('nao da pra acreditar no que ela me contou','surpresa'),
('os convidados ja estao chegando!','surpresa'),
('puxa vida! nunca nos livramos de alguem tao depressa','surpresa'),
('minha carteira sumiu, eu estava com ela na mao','surpresa'),
('oh! um disco voador','surpresa'),
('amigos, que bela surpresa!','surpresa'),
('nunca pensei que veria isso de perto','surpresa'),
('nem acredito que comi tanto','surpresa'),
('nao acredito que veio me ver','surpresa'),
('nao acredito que e tao bonito','surpresa'),
('me surpreende sua falta de tato','surpresa'),
('o predio onde eles moravam desabou!','surpresa'),
('inacreditavel um bolo tao grande','surpresa'),
('e serio mesmo? nao da para acreditar','surpresa'),
('como assim nao vai ao nosso encontro?!','surpresa'),
('como assim nao tem ninguem em casa?!','surpresa'),
('mas para onde ele foi?!','surpresa'),
('por essa eu nao esperava','surpresa'),
('nossa, olha so que mergulho','surpresa'),
('minha esposa esta gravida!','surpresa'),
('meu dinheiro sumiu!','surpresa'),
('e verdade que os dois terminaram?!','surpresa'),
('caramba, nem vi voce chegar','surpresa'),
('nossa, como pode alguem cozinhar tao mal?!','surpresa'),
('nossa que incrivel','surpresa'),
('a formula sumiu!','surpresa'),
('eu nem acredito que ja estou terminando o curso','surpresa'),
('nao acredito que esta aqui comigo novamente','surpresa'),
('voce esta escondendo algo de nos!','surpresa'),
('como assim voce ainda nao terminou a tarefa?!','surpresa'),
('pensei que ja estivesse pronta!','surpresa'),
('quem apagou a luz?!','surpresa'),
('caramba! aonde vai tao rapido?','surpresa'),
('estamos seguindo o caminho errado!','surpresa'),
('quatro reais o litro da gasolina!','surpresa'),
('me assustei ao ve-lo desse jeito!','surpresa'),
('minha mae esta gravida! acredita nisso?','surpresa'),
('parece mentira voce ter crescido tanto','surpresa'),
('me surpreende sua imaginacao','surpresa'),
('suas roupas sao realmente lindas!','surpresa'),
('como consegue ser tao bela?!','surpresa'),
('essa e realmente uma casa deslumbrante','surpresa'),
('superou minhas expectativas','surpresa'),
('e admiravel a maneira como se comporta','surpresa'),
('isso e realmente chocante','surpresa'),
('algumas noticias me surpreenderam no noticiario','surpresa'),
('surpreendente sua festa','surpresa'),
('estou tremendo de alegria','surpresa'),
('chocou grande parte do mundo','surpresa'),
('eu ficaria muito espantado com a sua vinda','surpresa'),
('ele e admiravel!','surpresa'),
('sua beleza me surpreendeu','surpresa'),
('seus olhos sao surpreendentemente verdes','surpresa'),
('os politicos se surpreendem quando alguem acredita neles','surpresa'),
('estou perplexa com essas denuncias','surpresa'),
('fiquei perplexo com suas palavras','surpresa'),
('estou abismado com sua prosa','surpresa'),
('eu ficaria realmente abismado se me dissessem isso','surpresa'),
('o grupo foi surpreendido enquanto lavava o carro','surpresa'),
('estou boquiaberto com as imagens','surpresa'),
('estou boquiaberto com essas suas palavras','surpresa'),
('esse quadro e maravilhoso','surpresa'),
('este carro me deixou maravilhado','surpresa'),
('estou maravilhada','surpresa'),
('essa expectativa esta me matando','surpresa'),
('vou caminhar sempre na expectativa de encontra-lo','surpresa'),
('voce emudece minhas palavras','surpresa'),
('minhas palavras vao emudecer se nao parar de me surpreender','surpresa'),
('a mulher e um efeito deslumbrante da natureza','surpresa'),
('estou deslumbrada com essas joias','surpresa'),
('isso e romantico e deslumbrante','surpresa'),
('isso pode ser surpreendentemente deslumbrante','surpresa'),
('trabalho deslumbrante','surpresa'),
('essas pessoas sao esplendidas','surpresa'),
('e esplendido como o ceu se encontra no momento','surpresa'),
('e um carro fantastico','surpresa'),
('um edifÌcio realmente fantastico','surpresa'),

('por favor nao me abandone','tristeza'),
('nao quero ficar sozinha','tristeza'),
('nao me deixe sozinha','tristeza'),
('estou abatida','tristeza'),
('ele esta todo abatido','tristeza'),
('tao triste suas palavras','tristeza'),
('seu amor nao e mais meu','tristeza'),
('estou triste','tristeza'),
('isso vai me aborrecer','tristeza'),
('estou com muita aflicao','tristeza'),
('me aflige o modo como fala','tristeza'),
('estou em agonia com meu intimo','tristeza'),
('nao quero fazer nada','tristeza'),
('me sinto ansiosa e tensa','tristeza'),
('nao consigo parar de chorar','tristeza'),
('nao consigo segurar as lagrimas','tristeza'),
('e muita dor perder um ente querido','tristeza'),
('estou realmente arrependida','tristeza'),
('acho que o carma volta, pois agora sou eu quem sofro','tristeza'),
('voce nao cumpriu suas promessas','tristeza'),
('me sinto amargurada','tristeza'),
('coitado esta tao triste','tristeza'),
('ja e tarde de mais','tristeza'),
('nosso amor acabou','tristeza'),
('essa noite so me machucou','tristeza'),
('eu nao estou mais no seu coracao','tristeza'),
('voce mudou comigo','tristeza'),
('quando eu penso em voce realmente doi','tristeza'),
('como se fosse nada voce ve minhas lagrimas','tristeza'),
('voce disse cruelmente que nao se arrependeu','tristeza'),
('eu nunca mais vou te ver','tristeza'),
('ela esta com depressao','tristeza'),
('a depressao aflige as pessoas','tristeza'),
('estar depressivo e muito ruim','tristeza'),
('estou derrotada e deprimida depois deste dia','tristeza'),
('e triste te ver dessa maneira','tristeza'),
('e triste ver o que as criancas do brasil passam','tristeza'),
('como me sinto culpada','tristeza'),
('estou abatida','tristeza'),
('a ansiedade tomou conta de mim','tristeza'),
('as pessoas nao gostam do meu jeito','tristeza'),
('adeus, passamos bons momentos juntos','tristeza'),
('sinto sua falta','tristeza'),
('ele nao gostou da minha comida','tristeza'),
('estou sem dinheiro para a comida','tristeza'),
('queria que fosse o ultimo dia da minha vida','tristeza'),
('voce esta com vergonha de mim','tristeza'),
('ela nao aceitou a minha proposta','tristeza'),
('era o meu ultimo centavo','tristeza'),
('reprovei de ano na faculdade','tristeza'),
('afinal voce so sabe me desfazer','tristeza'),
('eu falhei em tudo nessa vida','tristeza'),
('eu fui muito humilhado','tristeza'),
('e uma historia muito triste','tristeza'),
('ninguem acredita em mim','tristeza'),
('eu nao sirvo para nada mesmo','tristeza'),
('droga, nao faco nada direito','tristeza'),
('sofrimento em dobro na minha vida','tristeza'),
('fui demitida essa semana','tristeza'),
('as criancas sofrem ainda mais que os adultos','tristeza'),
('para mim um dia e ruim, o outro e pior','tristeza'),
('de repente perdi o apetite','tristeza'),
('oh que dia infeliz','tristeza'),
('estamos afundados em contas','tristeza'),
('nem um milagre pode nos salvar','tristeza'),
('so me resta a esperanca','tristeza'),
('pior que isso nao pode ficar','tristeza'),
('meu salario e baixo','tristeza'),
('nao passei no vestibular','tristeza'),
('ninguem se importa comigo','tristeza'),
('ninguem lembrou do meu aniversario','tristeza'),
('tenho tanto azar','tristeza'),
('o gosto da vinganca e amargo','tristeza'),
('sou uma mulher amargurada depois de que voce me deixou','tristeza'),
('estou desanimada com a vida','tristeza'),
('e um desanimo so coitadinha','tristeza'),
('a derrota e depressiva','tristeza'),
('discriminar e desumano','tristeza'),
('que desanimo','tristeza'),
('e uma desonra para o pais','tristeza'),
('a preocupacao deveria nos levar a acao, nao a depressao','tristeza'),
('passamos ao desalento e a loucura','tristeza'),
('aquele que nunca viu a tristeza nunca reconhecera a alegria','tristeza'),
('cuidado com a tristeza ela e um vicio','tristeza')]



baseteste =[('nao precisei pagar o ingresso','alegria'),
('se eu ajeitar tudo fica bem','alegria'),
('minha fortuna ultrapassa a sua','alegria'),
('sou muito afortunado','alegria'),
('e benefico para todos esta nova medida','alegria'),
('ficou lindo','alegria'),
('achei esse sapato muito bonito','alegria'),
('estou ansiosa pela sua chegada','alegria'),
('congratulacoes pelo seu aniversario','alegria'),
('delicadamente ele a colocou para dormir','alegria'),
('a musica e linda','alegria'),
('sem musica eu nao vivo','alegria'),
('conclui uma tarefa muito dificil','alegria'),
('conclui minha graduacao','alegria'),
('estou muito contente com tudo','alegria'),
('eu confio em voce','alegria'),
('e um prazer conhece-lo','alegria'),
('a relacao de voces e animadora','alegria'),
('estou aproveitando as ferias','alegria'),
('vamos aproveitar as ferias','alegria'),
('e muito divertido este jogo','alegria'),
('vamos ter muita diversao','alegria'),
('nao achei que me divertiria tanto assim','alegria'),
('vou consentir o orcamento ao cliente','alegria'),
('com o consentimento dos meus pais podemos nos casar','alegria'),
('eu adorei este perfume','alegria'),
('sua bondade e cativante','alegria'),
('estou despreocupada','alegria'),
('nao me preocupo com o que aconteceu','alegria'),
('me sinto completamente segura','alegria'),
('estimo muito o seu trabalho','alegria'),
('somos estimados por nossa familia','alegria'),
('concretizamos nossa ideia','alegria'),
('nosso ideal foi alcancado','alegria'),
('estamos muito felizes juntos','alegria'),
('estou tao animada com os preparativos para o casamento','alegria'),
('voce sera muito amado meu filho','alegria'),
('os apaixonados sao maravilhosos','alegria'),
('agradeco imensamente o seu apoio nestes dias','alegria'),
('esta comida me parece muito deliciosa','alegria'),
('voce me completa','alegria'),
('poderemos completar o projeto hoje!','alegria'),
('estamos namorando','alegria'),
('estou de olho neste vestido a um tempo','alegria'),
('pude comprar meu celular hoje','alegria'),
('e um deleite poder compartilhar minhas vitorias','alegria'),
('ela e um boa garota','alegria'),
('estivemos em um otimo show','alegria'),

('o mundo e feio como o pecado','desgosto'),
('a coisa mais difÌcil de esconder e aquilo que nao existe','desgosto'),
('voce errou feio aquele gol','desgosto'),
('nunca vou me casar sou muito feia','desgosto'),
('os golpes da adversidade sao terrivelmente amargos','desgosto'),
('os homem ficam terrivelmente chatos','desgosto'),
('abominavelmente convencido','desgosto'),
('terrivelmente irritado','desgosto'),
('as instituicoes publicas estao terrivelmente decadentes','desgosto'),
('a populacao viveu em isolamento por muito tempo','desgosto'),
('estou terrivelmente preocupada','desgosto'),
('o nacionalismo e uma doenca infantil','desgosto'),
('se me es antipatico a minha negacao esta pronta','desgosto'),
('muitos documentarios sobre esse casal antipatico','desgosto'),
('sua beleza nao desfara sua antipatia','desgosto'),
('esta e uma experiencia desagradavel','desgosto'),
('desagradavel estrago nos banheiros','desgosto'),
('o mais irritante no amor e que se trata de um crime que precisa de um cumplice','desgosto'),
('a situacao nos causa grande incomodo','desgosto'),
('estou preocupado com o incomodo na garganta','desgosto'),
('simplesmente nao quero amolacao da policia','desgosto'),
('voce e uma pessoa muito impertinente','desgosto'),
('o peso e a dor da vida','desgosto'),
('me arrependo amargamente de minhas acoes','desgosto'),
('o destino e cruel e os homens nao sao dignos de compaixao','desgosto'),
('o odio conduz ao isolamento cruel e ao desespero','desgosto'),
('encerrou com o massacre mais repudiavel e asqueroso que se conhece','desgosto'),
('de mal gosto e asqueroso','desgosto'),
('tudo e inserto neste mundo hediondo','desgosto'),
('o crime de corrupcao e um crime hediondo','desgosto'),
('o rio esta fetido e de cor escura','desgosto'),
('muito lixo no rio o deixa mal cheiroso','desgosto'),
('existe uma laranja podre no grupo e ja desconfiamos quem seja','desgosto'),
('de repente estou machucado e me sentindo enjoado','desgosto'),
('eu fiquei enojado','desgosto'),
('daqui alguns meses vou embora deste pais que ja estou nauseado','desgosto'),

('que abominavel esse montro!','medo'),
('vamos alarmar a todos sobre a situacao','medo'),
('estou amedrontada','medo'),
('estou com muito medo da noite','medo'),
('ele esta me ameacando a dias','medo'),
('quanta angustia','medo'),
('estou angustiada','medo'),
('angustiadamente vou sair e casa','medo'),
('isso me deixa apavorada','medo'),
('voce esta me apavorando','medo'),
('estou desconfiada de voce','medo'),
('nao confio em voce','medo'),
('ate o cachorro esta apavorado','medo'),
('estou assustado com as acoes do meu colega','medo'),
('agora se sente humilhado e apavorado','medo'),
('assustou a populacao e provocou mortes','medo'),
('estou com dificuldades para respirar e muito assustado','medo'),
('os policiais se assustaram quando o carro capotou','medo'),
('o trabalhador e assombrado pelo temor do desemprego','medo'),
('este lugar e mal assombrado','medo'),
('estou assombrado pela crise financeira','medo'),
('mesmo aterrorizado lembro de voce','medo'),
('aterrorizado e suando frio','medo'),
('um grupo de elefantes selvagens tem aterrorizado vilas','medo'),
('me sinto intimidada pela sua presenca','medo'),
('tenho medo de ser advertida novamente','medo'),
('estou correndo o risco de ser advertido','medo'),
('estou correndo riscos de saude','medo'),
('os riscos sao reais','medo'),
('podemos perder muito dinheiro com essa investida','medo'),
('socorro, fui intimado a depor','medo'),
('fui notificado e estou com medo de perder a guarda da minha filha','medo'),
('estou angustiada com meus filhos na rua','medo'),
('e abominavel o que fazem com os animais','medo'),
('foi terrivel, o tigre quase o matou','medo'),
('me advertiram sobre isso','medo'),

('ate que enfim, nao aguentava mais te esperar','raiva'),
('eu quero meu dinheiro de volta agora!','raiva'),
('eu odeio a escola!','raiva'),
('vou fazer picadinho de voce','raiva'),
('detesto trabalhar no verao','raiva'),
('quero minha comida, e quero agora!','raiva'),
('melhor voce recolher minhas compras agora!','raiva'),
('quero descer agora sua maluca','raiva'),
('vou reclamar com o gerente!','raiva'),
('vai engolir o que disse!','raiva'),
('ele me ridiculariza diante de todos','raiva'),
('nao quero mais saber de voce','raiva'),
('vejo voce na cadeia safado!','raiva'),
('agora vou ter que pagar mais isso ainda!','raiva'),
('saia logo do banheiro!','raiva'),
('suba ja para o seu quarto!','raiva'),
('eu falei para calar a boca seu idiota!','raiva'),
('eu disse para voce cair fora!','raiva'),
('nao aguento mais que fiquem me culpando sem motivo!','raiva'),
('nao suporto olhar na sua cara!','raiva'),
('eu nao sou um elefante','raiva'),
('juro que se olhar pra mim eu o mato!','raiva'),
('chega, nao quero saber mais deste assunto','raiva'),
('como pode ser tao burro?','raiva'),
('nao me aborreca seu moleque','raiva'),
('nao quero me aborrecer com estas bobagens','raiva'),
('ele me agrediu!','raiva'),
('eu amaldicoou voce e a sua famÌlia','raiva'),
('nao me amole','raiva'),
('nao venha me amolar','raiva'),
('isso tudo e uma tormenta','raiva'),
('eu vou matar voce','raiva'),
('para que simplificar se voce pode sempre complicar','raiva'),
('isso esta me enlouquecendo','raiva'),
('estou furiosa com voce','raiva'),
('isso mesmo fique furioso','raiva'),

('esses livros sao magnificos','surpresa'),
('esse vinho e magnifico','surpresa'),
('seria magnifico ver o espetaculo','surpresa'),
('o casamento foi estupendo','surpresa'),
('e um jogador estupendo','surpresa'),
('esse dia esta excelente','surpresa'),
('o cantor estava excelente','surpresa'),
('o universo e surpreendente','surpresa'),
('o amor e sublime','surpresa'),
('sua sublime atuacao','surpresa'),
('e formidavel meu caro walter','surpresa'),
('como e formidavel a presenca de todos','surpresa'),
('e formidavel ter a quem dizer adeus','surpresa'),
('e um conselheiro formidavel o seu','surpresa'),
('o artigo foi formidavel','surpresa'),
('pica pau e um destaque no imaginario brasileiro','surpresa'),
('ah! o absoluto do imaginario','surpresa'),
('isso foi surreal','surpresa'),
('uma historia completamente surreal','surpresa'),
('essas pinturas beiram o surreal','surpresa'),
('voce nem acreditam de tao surreal','surpresa'),
('incrivel!','surpresa'),
('fiquei pasma com tudo isso','surpresa'),
('voce me deixa pasmo','surpresa'),
('estou admirado com a sua astucia','surpresa'),
('que bela surpresa voce me fez','surpresa'),
('nao acredito que fez isso!','surpresa'),
('isso foi apavorante','surpresa'),
('isso tao de repente','surpresa'),
('estou chocada com isso','surpresa'),
('estou surpresa e desconsertada','surpresa'),
('esta realmente deslumbrante querida','surpresa'),
('fiquei completamente sem plavras','surpresa'),
('e espantoso o modo como ele nos olha','surpresa'),
('incrivel voce estar aqui','surpresa'),
('que fantastica festa minha querida','surpresa'),

('isso tudo e um erro','tristeza'),
('eu sou errada eu sou errante','tristeza'),
('tenho muita do do cachorro','tristeza'),
('e dolorida a perda de um filho','tristeza'),
('essa tragedia vai nos abalar para sempre','tristeza'),
('perdi meus filhos','tristeza'),
('perdi meu curso','tristeza'),
('sou so uma chorona','tristeza'),
('voce e um chorao','tristeza'),
('se arrependimento matasse','tristeza'),
('me sinto deslocado em sala de aula','tristeza'),
('foi uma passagem funebre','tristeza'),
('nossas condolencias e tristeza a sua perda','tristeza'),
('desanimo, raiva, solidao ou vazio, depressao','tristeza'),
('vivo te desanimando','tristeza'),
('estou desanimado','tristeza'),
('imperador sanguinario, depravado e temeroso','tristeza'),
('meu ser esta em agonia','tristeza'),
('este atrito entre nos tem que acabar','tristeza'),
('a escuridao desola meu ser','tristeza'),
('sua falsa preocupacao','tristeza'),
('sua falsidade me entristece','tristeza'),
('quem esta descontente com os outros esta descontente consigo mesmo','tristeza'),
('a torcida esta descontente com a demissao do tecnico','tristeza'),
('estou bastante aborrecido com o jornal','tristeza'),
('me sinto solitario e entediado','tristeza'),
('a vida e solitaria para aqueles que nao sao falsos','tristeza'),
('como com compulsao depois da depressao','tristeza'),
('estou me desencorajando a viver','tristeza'),
('ele desencoraja minhas vontades','tristeza'),
('isso vai deprimindo por dentro','tristeza'),
('acho que isso e defeituoso','tristeza'),
('os remedios me derrubam na cama','tristeza'),
('a depressao vai me derrubar','tristeza'),
('suas desculpas sao falsas','tristeza'),
('nao magoe as pessoas','tristeza')]



'''stopwords = ['a', 'agora', 'algum', 'alguma', 'aquele', 'aqueles', 'de', 'deu', 'do', 'e', 'estou', 'esta', 'esta',
             'ir', 'meu', 'muito', 'mesmo', 'no', 'nossa', 'o', 'outro', 'para', 'que', 'sem', 'talvez', 'tem', 'tendo',
             'tenha', 'teve', 'tive', 'todo', 'um', 'uma', 'umas', 'uns', 'vou']'''

stopwordsNLTK = nltk.corpus.stopwords.words('portuguese')
stopwordsNLTK.append('vou')
stopwordsNLTK.append('tão')
stopwordsNLTK.append('não')
#print(stopwordsNLTK)

#Retira palavras que não têm relevância para o entendimento do contexto da base de dados
def remove_stopwords(texto):
        frases = []
        for (palavras, emocao) in texto:
                semStop = [p for p in palavras.split() if p not in stopwordsNLTK]
                frases.append((semStop, emocao))
        return frases

#print(remove_stopwords(base))

#Diminui as palvras ao seu radical
def aplica_stemmer(texto):
        stemmer = nltk.stem.RSLPStemmer()
        frasesStemming = []
        for (palavras, emocao) in texto:
                comStemming = [str(stemmer.stem(p)) for p in palavras.split() if p not in stopwordsNLTK]
                frasesStemming.append((comStemming, emocao))
        return frasesStemming

frasesComStemmingTraining = aplica_stemmer(basetreinamento)
frasesComStemmingTest = aplica_stemmer(baseteste)
#print(frasesComStemmingTraining)

#Busca todas as plavras existentes na base de dados
def busca_palavras(frases):
        todasPlavras = []
        for(palavras, emocao) in frases:
                todasPlavras.extend(palavras)
        return todasPlavras

palavrasTraining = busca_palavras(frasesComStemmingTraining)
palavrasTest = busca_palavras(frasesComStemmingTest)
#print(palavras)

#Retorna a frequência de cada palavra
def busca_frequencia(palavras):
        palavras = nltk.FreqDist(palavras)
        return palavras

frequenciaTraining = busca_frequencia(palavrasTraining)
frequenciaTest = busca_frequencia(palavrasTest)
#print(frequencia.most_common(50))

#Busca somente as palavras que não são repetidas
def busca_palavras_unicas(frequencia):
        freq = frequencia.keys()
        return freq

palavrasUnicasTraining = busca_palavras_unicas(frequenciaTraining)
palavrasUnicasTest = busca_palavras_unicas(frequenciaTest)
#print(palavrasUnicas)

#Retorna se uma determinada palavra existe ou não no documento
def extrator_palavras(documento):
        doc = set(documento)
        caracteristicas = {}
        for palavras in palavrasUnicasTraining:
                caracteristicas['%s' % palavras] = (palavras in doc)
        return caracteristicas

caracteristicasFrases = extrator_palavras(['am', 'nov', 'dia'])
#print(caracteristicasFrases)

baseCompletaTraining = nltk.classify.apply_features(extrator_palavras, frasesComStemmingTraining)
baseCompletaTest = nltk.classify.apply_features(extrator_palavras, frasesComStemmingTest)
#print(baseCompleta)


def remove_hashtag(text):
    words = text.split()
    for i in words:
        if i.startwith('#'):
            words.remove(i)

    text = ' '.join(words)
    return text


def remove_url(text):
    clean_text = re.match('(.*?)http.*?\s?(.*?)', text)
    if clean_text:
        return clean_text.group(1)
    else:
        return text


#####################################################CLASSIFICAÇÃO######################################################

#Constrói a tabela de probabilidade
classificador = nltk.NaiveBayesClassifier.train(baseCompletaTraining)

#print(classificador.labels())
#print(classificador.show_most_informative_features(20))

print(nltk.classify.accuracy(classificador, baseCompletaTest))

erros = []
for (frase, classe) in baseCompletaTest:
    resultado = classificador.classify(frase)
    if resultado != classe:
        erros.append((classe, resultado, frase))
        
# for (classe, resultado, frase) in erros:
#    print(classe, resultado, frase)


from nltk.metrics import ConfusionMatrix
esperado = []
previsto = []

for (frase, classe) in baseCompletaTest:
    resultado = classificador.classify(frase)
    previsto.append(resultado)
    esperado.append(classe)
#esperado = 'alegria alegria alegria alegria medo medo surpresa surpresa'.split()
#previsto = 'alegria alegria medo surpresa medo medo medo surpresa'.split()
matriz = ConfusionMatrix(esperado, previsto)
print(matriz)



teste = "eu sinto amor por voce"
teste_stemming = []
stemmer = nltk.stem.RSLPStemmer()

for (palavras) in teste.split():
        com_stemming = [p for p in palavras.split()]
        teste_stemming.append(str(stemmer.stem(com_stemming[0])))

#print(teste_stemming)

# novo = extrator_palavras(teste_stemming)
# print(novo)
#
# print(classificador.classify(novo))

# distribuicao = classificador.prob_classify(novo)
# for classe in distribuicao.samples():
#     print("%s: %f" % (classe, distribuicao.prob(classe)))
